config/routes.rb
Rails.application.routes.draw do
  resources :feeds do
    collection do
      post :confirm
    end
  end

  resources :sessions, only: [:new, :create, :destroy]
  resources :users, only: [:new, :create, :show]
  resources :favorites, only: [:create, :destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :feed
end

app/models/feed.rb
class Feed < ApplicationRecord
  belongs_to :user
  has_many :favorites, dependent: :destroy
  has_many :favorite_users, through: :favorites, source: :user
  mount_uploader :image, ImageUploader
end

app/models/user.rb
class User < ApplicationRecord
  validates :name, presence: true, length: { maximum: 30 }
  validates :email, presence: true, length: { maximum: 255 }
                    
  before_validation { email.downcase! }
  has_secure_password
  validates :password, length: { minimum: 6 }
  has_many :feeds
  has_many :favorites, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include SessionsHelper
  before_action :login_required

  private

  def login_required
    redirect_to new_session_path unless current_user
  end
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  def create
    favorite = current_user.favorites.create(blog_id: params[:blog_id])
    redirect_to blogs_path, notice: "#{favorite.blog.user.name}さんのブログをお気に入り登録しました"
  end

  def destroy
    favorite = current_user.favorites.find_by(id: params[:id]).destroy
    redirect_to blogs_path, notice: "#{favorite.blog.user.name}さんのブログをお気に入り解除しました"
  end
end

app/controllers/feeds_controller.rb
class FeedsController < ApplicationController
  before_action :set_feed, only: [:show, :edit, :update, :destroy]

  def index
    @feeds = Feed.all
  end

  def show
    @favorite = current_user.favorites.find_by(feed_id: @feed.id)
  end

  def new
    if params[:back]
      @feed = Feed.new(feed_params)
    else
      @feed = Feed.new
    end
  end

  def confirm
    @feed = current_user.feeds.build(feed_params)
    render :new if @feed.invalid?
  end

  def edit
  end

  def create
    @feed =  current_user.feeds.build(feed_params)
    if params[:back]
      render :new
    else
      if @feed.save
        redirect_to feeds_path, notice: "ブログを作成しました！"
      else
      render :new
      end
    end
  end

  def update
      if @feed.update(feed_params)
        redirect_to feeds_path, notice: "ブログを編集しました！"
      else
        render :edit
      end
  end

  def destroy
    @feed.destroy
    redirect_to feeds_path, notice: "ブログ削除しました！"
  end

  private
    
    def set_feed
      @feed = Feed.find(params[:id])
    end

    
    def feed_params
      params.require(:feed).permit(:content, :image, :image_cache)
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  skip_before_action :login_required, only: [:new, :create, :show]

  def new
  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      session[:user_id] = user.id
      redirect_to user_path(user.id)
    else
      flash[:danger] = 'ログインに失敗しました'
      render :new
  end

  def destroy
    session.delete(:user_id)
    flash[:notice] = 'ログアウトしました'
    redirect_to new_session_path
  end
end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_action :login_required, only: [:new, :create]

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to user_path(@user.id)
    else
      render :new
    end
  end

  def show
    @user = User.find(params[:id])
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/feeds_helper.rb
module FeedsHelper
  def choose_new_or_edit
    if action_name == 'new' || action_name == 'create'
      confirm_feeds_path
    elsif action_name == 'edit'
      feed_path
    end
  end
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

  def logged_in?
    current_user.present?
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/feeds/_form.html.erb
<%= form_with(model: @feed, local: true, url: choose_new_or_edit) do |form| %>
  <% if @feed.errors.any? %>
    <div id="error_explanation">
      <h2><%= @feed.errors.count %>件のエラーがあります。</h2>
      <ul>

      <% @feed.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="feed_title">
    <%= form.label :content %>
    <%= form.text_field :content %>
  </div>
  <div class="field">
    <%= form.label :image %>
    <%= form.file_field :image %>
    <%= form.hidden_field :image_cache %>
  </div>

  <div class="actions">
  <%= form.submit %>
<% end %>

<%= link_to "一覧画面にもどる", feeds_path %>
  

app/views/feeds/confirm.html.erb
<h1>確認画面</h1>
<%= form_with(model: @feed, url: feeds_path, local: true) do |form| %>
  <%= image_tag(@feed.image.url) if @feed.image && @feed.image.url %>
  <p>本文:<%= @feed.content %></p>
  <%= form.hidden_field :image_cache %>
  <%= form.hidden_field :content %>
  <%= form.submit "投稿する" %>
<% end %>

<%= form_with(model:@feed, url:new_feed_path, local:true, method:"get") do |form| %>
  <%= form.hidden_field :image_cache %>
  <%= form.hidden_field :content %>
  <%= form.submit "戻る", name: "back" %>
<% end %>

app/views/feeds/edit.html.erb
<h2>編集する</h2>

  <%= render 'form' %>

app/views/feeds/index.html.erb
<h1>一覧画面</h1>



<table class = "table">
  <tr>
    <th>内容</th>
    <th>投稿者</th>
  </tr>

<% @feeds.each do |feed| %>
  <tr>
    <td><%= feed.content %></td>
    <td><%= feed.user.name %></td>
    <td><%= image_tag feed.image.url %></td>
    <td><%= link_to '詳細', feed_path(feed.id) %></td>
    <td><%= link_to '編集', edit_feed_path(feed.id) %></td>
    <td><%= link_to '削除', feed_path(feed.id), method: :delete %></td>
  </tr>
<% end %>
</table>

<%= link_to '新しく投稿する', new_feed_path %>

app/views/feeds/new.html.erb
<h2>作成する</h2>

  <%= render 'form' %>

app/views/feeds/show.html.erb
<h1>詳細画面</h1>
<p>内容: <%= @feed.content %></p>

<p id="notice"><%= notice %></p>

<p>
  <strong>Image:</strong>
  <%= image_tag @feed.image.url %>
</p>

<%= link_to '編集', edit_feed_path(@feed) %> |
<%= link_to '戻る', feeds_path %>

<% unless @feed.user_id == current_user.id %>
  <% if @favorite.present? %>
    <%= link_to 'お気に入り解除する', favorite_path(id: @favorite.id), method: :delete, class: 'btn btn-danger' %>
  <% else %>
    <%= link_to 'お気に入りする', favorites_path(feed_id: @feed.id), method: :post, class: 'btn btn-primary' %>
  <% end %>
<% end %>

<p class="mt-3"><%= link_to "ブログ一覧画面にもどる", feeds_path %></p >

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FbcloneApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
   <header class="d-flex flex-column flex-md-row align-items-center bg-light bg-gradient p-2 px-md-4 mb-3 border-bottom shadow-sm">
    <h5 class="my-0 mr-md-auto font-weight-normal">BLOG APPLI</h5>
    <nav class="my-4 my-md-2 mr-md-6">

    <% if logged_in? %>
     <%= link_to "Profile", user_path(current_user.id) %>
     <%= link_to "Logout", session_path(current_user.id), method: :delete %>
    <% else %>
     <%= link_to "Sign up", new_user_path %>
     <%= link_to "Login", new_session_path %>
    <% end %>
    </nav>
  </header>
    <% flash.each do |key, value| %>
      <%= content_tag(:div, value, class: "#{key}") %>
    <% end %>

    

    <div class="container">
    

    <%= yield %>
    </div>
     <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js" integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI" crossorigin="anonymous"></script>
  </body>
</html>

app/views/tops/index.html.erb
<h1>Tops#index</h1>
<p>Find me in app/views/tops/index.html.erb</p>

app/views/users/new.html.erb
<h1>Sign up</h1>

<% if @user.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@user.errors.count, "error") %> prohibited this <%= @user.name %> from being saved:</h2>
    <ul>
    <% @user.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
    </ul>
  </div>
<% end %>

<%= form_with(model: @user, local: true) do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>

  <%= f.label :email %>
  <%= f.email_field :email %>

  <%= f.label :password %>
  <%= f.password_field :password %>

  <%= f.label :password_confirmation %>
  <%= f.password_field :password_confirmation %>

  <%= f.submit "Create my account" %>
<% end %>

app/views/users/show.html.erb
<h1><%= @user.name %>のページ</h1>

<p>メールアドレス: <%= @user.email %></p>